<?php
    $path = "../archives";
    $table = "performances";
    include "../archive.php";
?>
<!-- body starts in archive.php -->

                <div class="statement">
                <h2 class="centered sub-heading">collaboration with cat'o'nine-tails
                            (
                            <a href="https://www.instagram.com/_gr8fuldead_/">
                                instagram</a>
                            )
                            
                    </h2>
                    <h2  class="sub-heading">stephan e perez:</h2><p>My contribution to this piece was inspired by the book "Why Buddhism is True" by Robert Wright. Below are two passages from the book.&nbsp;</p><p></p><p><em>[...] Your mind is much calmer than usual, and you are viewing its contents much more objectively than usual. And some contents of your consciousness that you normally think of yourself as generating seem to be getting generated by something other than you. More than once I've heard a meditation teacher say, "Thoughts think themselves."</em></p><p></p><p><em>Mindfulness meditation [...] can let you experience your feelings-anger, love, sorrow, joy-with new sensitivity, seeing their texture, even feeling their texture, as never before.</em></p><p></p><h2 class="sub-heading">cat-o'-nine-tails:</h2><p>Ah! Good morning! I just woke up!</p><p>(By "I just woke up" I don't mean getting out of bed- but starting up, a comeback! And, uh... yeah. Where did I just get back from? Or maybe I'm not back, but I'm still out? Hmm... HMMMMM??! WHICH ONE IS IT?!?!? I'M... EVERYONE-------!!!! EVERYONE--------!!</p><p>Where is the border between me and everyone?&nbsp; I am... I am...&nbsp; anyway, the important thing is to just be myself. This is not me having a complex and being in denial about my evil "multiple personalities". I can't become sane. I used to think I wasn't bothering anyone, but I'm done with that. I'm done. I think I'll save the rest of my kindness for later)</p><p>Hey, everyone! Want to get a drink?</p><p>
                </div>   
                <p class="centered photo-vid-credits">
                    <em>video archive by bannai hidenari of ham tamago sandwich</em>
                </p>
                <p class="centered photo-vid-credits">
                    <em>photos by ma raven of ham tamago sandwich</em>
                </p>
                <?php include $rootDir . "footer.html";?>
            </main>
        </div>
    </body>
</html>