services:
  web:
    build: .
    container_name: sepsite-web-1
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=sep-common-db-1
      - DB_USER=root
      - DB_PASS=${SHARED_DB_PASSWORD}
      - DB_NAME=${DB_NAME:-sep_site}
      - DB_PORT=3306
    networks:
      - npm_default
      - sep_common_net

networks:
  npm_default:
    external: true
  sep_common_net:
    external: true
